### ISSUE TITLE
Ranking implementation?

### ISSUE THREAD

**Issue by berezovskyi** [filipdbrsk/LOTUS_Indexer#2]
I see that you are querying the resource degree, for example, at https://github.com/filipdbrsk/LOTUS_Indexer/blob/342548aa61c8be43a56f739ff406652aa059e5e8/lotus_v2.1.js#L111 but not where it is calculated.

I figured out that LOD Laundromat works with RocksDB so you much be using its data. I traced RocksDB operations to https://github.com/LOD-Laundromat/LOD-Laundromat/blob/2b9ff8f603598f1efc332d5ef4c220327c4679b0/ll3/ll_index.pl#L91 but then got lost :)

I interested in trying to get LOTUS up and running for myself locally.  Seems like I won't be able to just point LOTUS indexer at the SPARQL endpoint spin up the whole Laundromat infra. Is that right? I will try to contribute some docker scripts as I go along trying to run your project.

And yes, great job!

**Comment by filievski** [comment]
Hi Andrew,

Thanks for your pull requests and interest in LOTUS!

1) You are correct, there is no SPARQL endpoint that contains the entire Laundromat data (there is only one for the metadata at http://lodlaundromat.org/sparql/). To access the data, we typically stream it via the tool Frank: https://github.com/LOD-Laundromat/frank (you might be aware of these already but just to be complete here).

2) In the current architecture of LOD Laundromat, it is quite hard to create the two resource-based indices. We did not find a way to optimize these two to a sufficient extent for them to be easily setup locally, for two reasons: generating the subject-based data for rocksdb is expensive, and querying rocksdb for billions of entries is not quick with our current implementation. We are currently not working directly on this, except that we are working on Laundromat 3.0 (mainly Wouter) which is exactly meant to give better access to large RDF data. Anyway, what is needed to improve these 2 indices is a focused engineering effort, so if you would like to join forces, please get in touch with us. 
Otherwise, I'd suggest you ignore these 2 indices for now, and let's hope that Laundromat 3.0 will be out in not too long.
