### ISSUE TITLE
Limited literal support

### ISSUE THREAD

**Issue by berezovskyi** [filipdbrsk/LOTUS_Indexer#3]
LOTUS paper describes that literals with and without lang and with 2 unicode chars are considered by LOTUS (p. 476).

I was able to (actually it was @s87485759) a counterexample:

http://lotus.lodlaundromat.org/#?q=DBLP%20journals%2Fcorr%2Fabs-1204-0447&match=terms&rank=lengthnorm&langtag=

While the resource found by the http://lotus.lodlaundromat.org/#?q=How%20China%20Is%20Blocking%20Tor&match=phrase&rank=psf&langtag= query shows an `identifier` predicate with a literal. http://lotus.lodlaundromat.org/#?q=%221204.0447%22&match=terms&rank=lengthnorm&langtag= Returns no results either.

Is it the expected behaviour?

**Comment by filievski** [comment]
It is indeed the expected behavior Andrew. This is because when a query is sent by using the lotus GUI at http://lotus.lodlaundromat.org/, it is only querying the object fields of triples, and not the subject and the predicate fields. 

Note that the GUI is only exposing part of the LOTUS functionality. It was created with the purpose to introduce new users to roughly what LOTUS does. For the full set of functionalities, please use the API at http://lotus.lodlaundromat.org/retrieve. You can find the parameters for this API at http://lotus.lodlaundromat.org/docs (be prepared to see an 90s HTML design there :) )

The subjects and the predicates of triples are also indexed in LOTUS, so you can search for parts of them using the API. For instance, you can do the following call: http://lotus.lodlaundromat.org/retrieve?string=How%20China%20Is%20Blocking%20Tor&match=phrase&rank=psf&langtag=&subject=%22abs-1204-0447%22&uniq=true
to get all triples with the specified string and subject.

Hope this helps!
